apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: project5-aws-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: project5-app-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: project5-aws-secrets
    kind: SecretStore

  target:
    name: project5-app-secret
    creationPolicy: Owner

  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: project5/rails/secret-key-base
